CREATE DATABASE IF NOT EXISTS VIA_DELAYS;
USE DATABASE VIA_DELAYS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;

CREATE TABLE IF NOT EXISTS RAW.STOP_OBSERVATIONS (
  TRAIN_NUMBER        STRING,
  SERVICE_DATE        DATE,
  STOP_SEQUENCE       NUMBER,
  STATION_CODE        STRING,
  SCHEDULED_ARRIVAL   TIMESTAMP_NTZ,
  ACTUAL_ARRIVAL      TIMESTAMP_NTZ,
  SCHEDULED_DEPARTURE TIMESTAMP_NTZ,
  ACTUAL_DEPARTURE    TIMESTAMP_NTZ,
  DELAY_MINUTES       FLOAT,
  SOURCE              STRING,
  SCRAPED_AT          TIMESTAMP_NTZ,
  PAYLOAD             VARIANT
);

CREATE TABLE IF NOT EXISTS RAW.JOB_RUNS (
  JOB_ID       STRING,
  KIND         STRING,
  STARTED_AT   TIMESTAMP_NTZ,
  FINISHED_AT  TIMESTAMP_NTZ,
  STATUS       STRING,
  ROW_COUNT    NUMBER,
  ERROR        STRING
);

CREATE TABLE IF NOT EXISTS RAW.WEATHER_OBSERVATIONS (
  STATION_CODE STRING,
  OBS_TIME     TIMESTAMP_NTZ,
  TEMP_C       FLOAT,
  PRECIP_MM    FLOAT,
  SNOW_CM      FLOAT,
  WIND_KPH     FLOAT,
  CONDITION    STRING
);
