USE DATABASE VIA_DELAYS;

CREATE OR REPLACE VIEW STAGING.STOP_DELAYS AS
SELECT
  TRAIN_NUMBER,
  SERVICE_DATE,
  STOP_SEQUENCE,
  STATION_CODE,
  SCHEDULED_ARRIVAL,
  ACTUAL_ARRIVAL,
  DELAY_MINUTES,
  SOURCE
FROM RAW.STOP_OBSERVATIONS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY TRAIN_NUMBER, SERVICE_DATE, STOP_SEQUENCE, SOURCE
  ORDER BY SCRAPED_AT DESC
) = 1;

CREATE OR REPLACE VIEW STAGING.TRAIN_RUNS AS
SELECT
  TRAIN_NUMBER,
  SERVICE_DATE,
  MIN(STATION_CODE) KEEP (DENSE_RANK FIRST ORDER BY STOP_SEQUENCE) AS ORIGIN_STATION,
  MAX(STATION_CODE) KEEP (DENSE_RANK LAST  ORDER BY STOP_SEQUENCE) AS DEST_STATION,
  MAX(DELAY_MINUTES) AS FINAL_DELAY_MINUTES,
  MAX(DELAY_MINUTES) AS MAX_DELAY_MINUTES,
  COUNT(*)           AS STOPS
FROM STAGING.STOP_DELAYS
GROUP BY TRAIN_NUMBER, SERVICE_DATE;
