USE DATABASE VIA_DELAYS;

CREATE TABLE IF NOT EXISTS MART.MODEL_FEATURES (
  TRAIN_NUMBER       STRING,
  SERVICE_DATE       DATE,
  ORIGIN_STATION     STRING,
  DEST_STATION       STRING,
  DOW                NUMBER,
  IS_WEEKEND         BOOLEAN,
  MONTH              NUMBER,
  HOUR               NUMBER,
  TRAIN_NUMBER_HASH  NUMBER,
  AVG_DELAY_L30D     FLOAT,
  AVG_DELAY_L30D_DOW FLOAT,
  WEATHER_PRECIP_MM  FLOAT,
  WEATHER_SNOW_CM    FLOAT,
  WEATHER_TEMP_C     FLOAT,
  TARGET_DELAY_MIN   FLOAT
);

CREATE TABLE IF NOT EXISTS MART.MODEL_RUNS (
  MODEL_ID     STRING,
  TRAINED_AT   TIMESTAMP_NTZ,
  ALGO         STRING,
  MAE          FLOAT,
  RMSE         FLOAT,
  FEATURES     VARIANT,
  ARTIFACT_URI STRING,
  IS_ACTIVE    BOOLEAN
);
